//! Network namespace (net_*) RPC handlers.

use std::sync::Arc;

use alloy_primitives::U64;
use jsonrpsee::core::RpcResult as JsonRpcResult;
use jsonrpsee::proc_macros::rpc;
use tracing::trace;

use crate::error::RpcError;
use crate::traits::NetworkApi;

/// Network namespace RPC trait.
///
/// This trait is auto-generated by jsonrpsee and provides both server and client
/// implementations for the net_* RPC methods.
#[rpc(server, namespace = "net")]
pub trait NetRpc {
    /// Returns the current network id.
    #[method(name = "version")]
    async fn version(&self) -> JsonRpcResult<String>;

    /// Returns true if client is actively listening for network connections.
    #[method(name = "listening")]
    async fn listening(&self) -> JsonRpcResult<bool>;

    /// Returns number of peers currently connected to the client.
    #[method(name = "peerCount")]
    async fn peer_count(&self) -> JsonRpcResult<U64>;
}

/// Network namespace RPC handler.
pub struct NetApi<N>
where
    N: NetworkApi,
{
    /// Network interface.
    network: Arc<N>,
    /// Network ID (same as chain ID for CipherBFT).
    network_id: u64,
}

impl<N> NetApi<N>
where
    N: NetworkApi,
{
    /// Create a new NetApi instance.
    pub fn new(network: Arc<N>, network_id: u64) -> Self {
        Self {
            network,
            network_id,
        }
    }
}

#[async_trait::async_trait]
impl<N> NetRpcServer for NetApi<N>
where
    N: NetworkApi + 'static,
{
    async fn version(&self) -> JsonRpcResult<String> {
        trace!("net_version");
        Ok(self.network_id.to_string())
    }

    async fn listening(&self) -> JsonRpcResult<bool> {
        trace!("net_listening");
        self.network
            .is_listening()
            .await
            .map_err(|e| RpcError::Internal(e.to_string()).into())
    }

    async fn peer_count(&self) -> JsonRpcResult<U64> {
        trace!("net_peerCount");
        let count = self
            .network
            .peer_count()
            .await
            .map_err(|e| RpcError::Internal(e.to_string()))?;
        Ok(U64::from(count))
    }
}
