//! Web3 namespace (web3_*) RPC handlers.

use alloy_primitives::{keccak256, Bytes, B256};
use jsonrpsee::core::RpcResult as JsonRpcResult;
use jsonrpsee::proc_macros::rpc;
use tracing::trace;

/// Web3 namespace RPC trait.
///
/// This trait is auto-generated by jsonrpsee and provides both server and client
/// implementations for the web3_* RPC methods.
#[rpc(server, namespace = "web3")]
pub trait Web3Rpc {
    /// Returns the current client version.
    #[method(name = "clientVersion")]
    async fn client_version(&self) -> JsonRpcResult<String>;

    /// Returns Keccak-256 (not the standardized SHA3-256) of the given data.
    #[method(name = "sha3")]
    async fn sha3(&self, data: Bytes) -> JsonRpcResult<B256>;
}

/// Web3 namespace RPC handler.
pub struct Web3Api {
    /// Client version string.
    version: String,
}

impl Web3Api {
    /// Create a new Web3Api instance with a custom version string.
    pub fn with_version(version: &str) -> Self {
        // Format: CipherBFT/v{version}/{os}
        let os = std::env::consts::OS;
        let version_str = format!("CipherBFT/v{}/{}", version, os);
        Self {
            version: version_str,
        }
    }

    /// Create a new Web3Api instance with default version.
    pub fn new() -> Self {
        Self::with_version(env!("CARGO_PKG_VERSION"))
    }
}

impl Default for Web3Api {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait::async_trait]
impl Web3RpcServer for Web3Api {
    async fn client_version(&self) -> JsonRpcResult<String> {
        trace!("web3_clientVersion");
        Ok(self.version.clone())
    }

    async fn sha3(&self, data: Bytes) -> JsonRpcResult<B256> {
        trace!("web3_sha3: {} bytes", data.len());
        Ok(keccak256(&data))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_client_version() {
        let api = Web3Api::with_version("0.1.0");
        assert!(api.version.starts_with("CipherBFT/v0.1.0/"));
    }

    #[tokio::test]
    async fn test_sha3() {
        let api = Web3Api::default();
        let data = Bytes::from_static(b"hello");
        let hash = api.sha3(data).await.unwrap();
        // Known keccak256 hash of "hello"
        assert_eq!(
            hex::encode(hash),
            "1c8aff950685c2ed4bc3174f3472287b56d9517b9c948127319a09a7a36deac8"
        );
    }
}
