#!/bin/bash
# Generate docker-compose.yml dynamically based on devnet configuration
#
# This script creates:
# - docker-compose.yml with one service per validator
# - Docker-specific node configs with container paths
# - Prometheus config for metrics collection
# - Grafana for visualization
#
# Usage:
#   ./scripts/generate-compose.sh [devnet_dir] [output_dir]
#
# Example:
#   ./scripts/generate-compose.sh ./devnet ./docker
#   ./scripts/generate-compose.sh  # defaults to ./devnet and ./docker

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
DEVNET_DIR="${1:-$PROJECT_ROOT/devnet}"
OUTPUT_DIR="${2:-$PROJECT_ROOT/docker}"

# Ensure the devnet directory exists
if [ ! -d "$DEVNET_DIR" ]; then
    echo "Error: Devnet directory not found: $DEVNET_DIR"
    echo ""
    echo "Initialize devnet first with:"
    echo "  cargo run -p cipherd -- devnet init-files --output $DEVNET_DIR"
    exit 1
fi

# Get absolute paths
DEVNET_DIR="$(cd "$DEVNET_DIR" && pwd)"
mkdir -p "$OUTPUT_DIR"
OUTPUT_DIR="$(cd "$OUTPUT_DIR" && pwd)"

# Find all node directories
NODES=$(ls -d "${DEVNET_DIR}"/node* 2>/dev/null | sort -V)

if [ -z "$NODES" ]; then
    echo "Error: No node directories found in $DEVNET_DIR"
    exit 1
fi

NODE_COUNT=$(echo "$NODES" | wc -l | tr -d ' ')

echo "Generating docker-compose.yml for $NODE_COUNT validators..."

# Calculate relative path from output dir to project root
RELATIVE_PATH=$(python3 -c "import os.path; print(os.path.relpath('$PROJECT_ROOT', '$OUTPUT_DIR'))")

# Create configs directory for Docker-specific configs
CONFIGS_DIR="$OUTPUT_DIR/configs"
mkdir -p "$CONFIGS_DIR"

# Generate Docker-specific node configs with container paths
echo "Generating Docker node configs..."
for NODE_DIR in $NODES; do
    NODE_NAME=$(basename "$NODE_DIR")
    NODE_NUM=${NODE_NAME#node}
    ORIGINAL_CONFIG="${NODE_DIR}/config/node.json"
    DOCKER_CONFIG_DIR="${CONFIGS_DIR}/${NODE_NAME}"
    mkdir -p "$DOCKER_CONFIG_DIR"
    DOCKER_CONFIG="${DOCKER_CONFIG_DIR}/node.json"

    if [ ! -f "$ORIGINAL_CONFIG" ]; then
        echo "Warning: Config not found: $ORIGINAL_CONFIG"
        continue
    fi

    # Transform config paths for Docker container
    # Also update peer addresses to use Docker container names
    python3 << PYEOF
import json
import re

with open("$ORIGINAL_CONFIG") as f:
    config = json.load(f)

# Update paths to container paths
config["keystore_dir"] = "/app/keys"
config["home_dir"] = "/app"
config["data_dir"] = "/app/data"
config["genesis_path"] = "/app/genesis.json"

# Update peer addresses to use Docker container names
# Map 127.0.0.1:90X0 -> validator-X:90X0
for peer in config.get("peers", []):
    for key in ["primary_addr", "consensus_addr"]:
        if key in peer:
            addr = peer[key]
            # Extract port to determine which node this is
            match = re.match(r"127\.0\.0\.1:(\d+)", addr)
            if match:
                port = int(match.group(1))
                # Port pattern: 9000, 9010, 9020... -> node 0, 1, 2...
                peer_node_num = (port - 9000) // 10
                peer[key] = f"validator-{peer_node_num}:{port}"

    # Update worker addresses
    if "worker_addrs" in peer:
        new_addrs = []
        for addr in peer["worker_addrs"]:
            match = re.match(r"127\.0\.0\.1:(\d+)", addr)
            if match:
                port = int(match.group(1))
                peer_node_num = (port - 9000) // 10
                new_addrs.append(f"validator-{peer_node_num}:{port}")
            else:
                new_addrs.append(addr)
        peer["worker_addrs"] = new_addrs

with open("$DOCKER_CONFIG", "w") as f:
    json.dump(config, f, indent=2)
PYEOF

    echo "  Generated: $DOCKER_CONFIG"
done

# Start composing the docker-compose.yml
COMPOSE_FILE="$OUTPUT_DIR/docker-compose.yml"

cat > "$COMPOSE_FILE" << 'EOF'
# Auto-generated by generate-compose.sh
# DO NOT EDIT MANUALLY - regenerate with: ./scripts/generate-compose.sh

services:
EOF

# Generate validator services
NODE_INDEX=0
PROMETHEUS_TARGETS=""

for NODE_DIR in $NODES; do
    NODE_NAME=$(basename "$NODE_DIR")
    NODE_NUM=${NODE_NAME#node}

    # Calculate port offsets (base ports: 8545, 8546, 9100)
    RPC_HTTP_PORT=$((8545 + NODE_INDEX * 10))
    RPC_WS_PORT=$((8546 + NODE_INDEX * 10))
    METRICS_PORT=$((9100 + NODE_INDEX))

    # Build prometheus targets list
    if [ -n "$PROMETHEUS_TARGETS" ]; then
        PROMETHEUS_TARGETS="${PROMETHEUS_TARGETS}
        - 'validator-${NODE_NUM}:9100'"
    else
        PROMETHEUS_TARGETS="        - 'validator-${NODE_NUM}:9100'"
    fi

    cat >> "$COMPOSE_FILE" << EOF
  validator-${NODE_NUM}:
    build:
      context: ${RELATIVE_PATH}
      dockerfile: Dockerfile
    container_name: cipherbft-validator-${NODE_NUM}
    command: ["start", "--config", "/app/config/node.json"]
    volumes:
      - ./configs/${NODE_NAME}:/app/config:ro
      - ${RELATIVE_PATH}/devnet/${NODE_NAME}/keys:/app/keys:ro
      - ${RELATIVE_PATH}/devnet/${NODE_NAME}/data:/app/data
      - ${RELATIVE_PATH}/devnet/genesis.json:/app/genesis.json:ro
    ports:
      - "${RPC_HTTP_PORT}:8545"
      - "${RPC_WS_PORT}:8546"
      - "${METRICS_PORT}:9100"
    networks:
      - cipherbft
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

EOF

    NODE_INDEX=$((NODE_INDEX + 1))
done

# Add monitoring services
cat >> "$COMPOSE_FILE" << 'EOF'
  prometheus:
    image: prom/prometheus:v2.50.0
    container_name: cipherbft-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
    ports:
      - "9090:9090"
    networks:
      - cipherbft
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.3.0
    container_name: cipherbft-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    networks:
      - cipherbft
    depends_on:
      - prometheus
    restart: unless-stopped

networks:
  cipherbft:
    driver: bridge
EOF

echo "Generated: $COMPOSE_FILE"

# Generate prometheus config
PROMETHEUS_DIR="$OUTPUT_DIR/prometheus"
mkdir -p "$PROMETHEUS_DIR"
PROMETHEUS_FILE="$PROMETHEUS_DIR/prometheus.yml"

cat > "$PROMETHEUS_FILE" << EOF
# Auto-generated by generate-compose.sh
# DO NOT EDIT MANUALLY - regenerate with: ./scripts/generate-compose.sh

global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'cipherbft'
    static_configs:
      - targets:
${PROMETHEUS_TARGETS}
        labels:
          network: 'devnet'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
EOF

echo "Generated: $PROMETHEUS_FILE"
echo ""
echo "Docker Compose configuration generated for $NODE_COUNT validators."
